version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - T-dependencies
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"

  # Ensure that references to actions in a repository's workflow.yml file are kept up to date.
  # See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      # Mark PRs as CI related change.
      - T-CI
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"